FROM php:8.2-rc-apache

RUN apt-get update && apt-get install -y \
		libzip-dev \
        libxml2-dev \
        libcurl4-openssl-dev \
        libgd3 \
        libpng-dev


RUN docker-php-ext-install zip xml curl gd opcache

RUN a2enmod ssl
RUN a2enmod rewrite

EXPOSE 80
EXPOSE 443